# Generated by Django 3.1.7 on 2021-04-11 17:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20210410_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
