# Generated by Django 3.1.7 on 2021-04-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20210411_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='restor', max_length=55),
        ),
    ]
