# Generated by Django 3.1.7 on 2021-04-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
